name = "AffineA"
uuid = "ab33c73e-65dd-48ee-85bc-110004cc0c76"
authors = ["Jean Michel <jean.michel@imj-prg.fr>"]
version = "0.1.0"

[deps]
Gapjm = "367f69f0-ca63-11e8-2372-438b29340c1b"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
